export {
  cellIndex,
  cellPosition,
  cooperatorShare,
  createSpatialConfig,
  neighborsOf,
  runSpatial,
  scoreGrid,
  seededGrid,
  singleDefectorGrid,
  stepGrid,
  type Boundary,
  type Neighborhood,
  type SpatialConfig,
  type SpatialGeneration,
  type SpatialGrid,
  type SpatialRun,
  type SpatialStrategy,
  type SpatialTermination,
} from "@/engine/spatial/lattice";
